version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      - NPM_CONFIG_LOGLEVEL: "silent"
    steps:
      - checkout
      - restore_cache:
          key: root-{{ checksum "package.json" }}
      - restore_cache:
          key: chimp-{{ checksum "chimp/package.json" }}
      - restore_cache:
          key: test-project-{{ checksum "test-project/package.json" }}
      - run: npm run setup
      - save_cache:
          key: root-{{ checksum "package.json" }}
          paths:
            - node_modules
            - .eslintcache
      - save_cache:
          key: chimp-{{ checksum "chimp/package.json" }}
          paths:
            - chimp/node_modules
            - dist/node_modules
      - save_cache:
          key: test-project-{{ checksum "test-project/package.json" }}
          paths:
            - test-project/node_modules
      - run: npm run test